#!/usr/bin/env bash

# project dir
path=$(realpath "$0" | sed 's|\(.*\)/.*|\1|')
# echo $path
cd $path

if [ ! -z $1 ]; then 
  [[ $1 == "fetch" ]] && python3 "fetch.py" || echo "invalid command: try 'kindle-high fetch'"; exit 1;
fi

python3 "print.py"
