#!/usr/bin/env bash

# project dir
path=$(realpath "$0" | sed 's|\(.*\)/.*|\1|')
# echo $path
cd $path

if [ ! -z $1 ]; then 
  [[ $1 == "fetch" ]] && python3 "fetch.py" || echo "invalid command: try 'fetch'"; exit 1;
fi

# Calling prompt
python3 "prompt.py"
